name: Build Slides Didattica Innovativa
on:
  push:
    paths:
    - 'presentazioneDI/slides/Metodi_multistep.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: Metodi_multistep.tex
          working_directory: presentazioneDI/slides/
      - name: Check pdf file
        run: |
          file ./presentazioneDI/slides/Metodi_multistep.pdf | grep -q ' PDF '
      - name: Commit files
        run: |
          git config --local user.email "${{ secrets.MY_EMAIL }}"
          git config --local user.name "${{ secrets.MY_NAME }}"
          git add -f ./presentazioneDI/slides/Metodi_multistep.pdf
          git commit -m "[ROBOT] Slides compilate automaticamente"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
